# Generated by Django 4.0.7 on 2022-09-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='Опис '),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Опис '),
        ),
    ]
