# Generated by Django 4.0.7 on 2022-09-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_variants_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='is_right',
            field=models.BooleanField(null=True, verbose_name='Чи є відповідь правильною'),
        ),
    ]
