# Generated by Django 4.0.7 on 2022-09-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_variants_is_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Point',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Ціна замовлення'),
        ),
    ]
