# Generated by Django 4.0.7 on 2022-09-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_answer_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Point',
            new_name='point',
        ),
    ]
